aliases: []
creation_timestamp: 1690882721682
current_stage: Production
description: null
last_updated_timestamp: 1690882755001
name: convolution
run_id: 076ad437da3e40b686c242a9eb855fee
run_link: null
source: /home/borja/projects/deepaas_full/models/0/076ad437da3e40b686c242a9eb855fee/artifacts/model
status: READY
status_message: null
user_id: null
version: 1
