aliases: []
creation_timestamp: 1690890001284
current_stage: Production
description: null
last_updated_timestamp: 1690890009145
name: convolution
run_id: e08501ef1ef846e8a07d4fb2bc24436a
run_link: null
source: /home/borja/projects/deepaas_full/models/0/e08501ef1ef846e8a07d4fb2bc24436a/artifacts/model
status: READY
status_message: null
user_id: null
version: 2
