artifact_uri: /home/borja/projects/demo-advanced-api/models/0/bbe3ef9450f747b9a34e99e3f3f43bd3/artifacts
end_time: 1690880557064
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bbe3ef9450f747b9a34e99e3f3f43bd3
run_name: kindly-kite-828
run_uuid: bbe3ef9450f747b9a34e99e3f3f43bd3
source_name: ''
source_type: 4
source_version: ''
start_time: 1690880389965
status: 3
tags: []
user_id: borja
