stages:
  convolution_t10k:
    cmd: python -m deepaas_full.data.make_convolution -o data/processed/t10k-convolution data/raw/t10k-images-idx3-ubyte.gz data/raw/t10k-labels-idx1-ubyte.gz
    deps:
    - data/raw/t10k-images-idx3-ubyte.gz
    - data/raw/t10k-labels-idx1-ubyte.gz
    outs:
    - data/processed/t10k-convolution.npz
  convolution_t60k:
    cmd: python -m deepaas_full.data.make_convolution -o data/processed/t60k-convolution data/raw/train-images-idx3-ubyte.gz data/raw/train-labels-idx1-ubyte.gz
    deps:
    - data/raw/train-images-idx3-ubyte.gz
    - data/raw/train-labels-idx1-ubyte.gz
    outs:
    - data/processed/t60k-convolution.npz
  autoencoder_t60k:
    cmd: python -m deepaas_full.data.make_autoencoder -o data/processed/t60k-autoencoder data/raw/train-images-idx3-ubyte.gz
    deps:
    - data/raw/train-images-idx3-ubyte.gz
    outs:
    - data/processed/t60k-autoencoder.npz
