stages:
  preprocess_t10k:
    cmd: python -m deepaas_full.data.make_dataset -o data/processed/t10k-dataset data/raw/t10k-images-idx3-ubyte.gz data/raw/t10k-labels-idx1-ubyte.gz
    deps:
    - data/raw/t10k-images-idx3-ubyte.gz
    - data/raw/t10k-labels-idx1-ubyte.gz
    outs:
    - data/processed/t10k-dataset.npz
  preprocess_train:
    cmd: python -m deepaas_full.data.make_dataset -o data/processed/train-dataset data/raw/train-images-idx3-ubyte.gz data/raw/train-labels-idx1-ubyte.gz
    deps:
    - data/raw/train-images-idx3-ubyte.gz
    - data/raw/train-labels-idx1-ubyte.gz
    outs:
    - data/processed/train-dataset.npz
  