digest: 5118c584
name: dataset
profile: '{"features_shape": [60000, 28, 28], "features_size": 47040000, "features_nbytes":
  376320000, "targets_shape": [60000, 10], "targets_size": 600000, "targets_nbytes":
  2400000}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float64\", \"shape\": [-1, 28, 28]}}]", "targets": "[{\"type\": \"tensor\",
  \"tensor-spec\": {\"dtype\": \"float32\", \"shape\": [-1, 10]}}]"}}'
source: '{"tags": {"mlflow.user": "borja", "mlflow.source.name": "/home/borja/projects/deepaas_full/deepaas_full/models/train_model.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "dd77c68d201901f524bfe26647402d6aebd93853"}}'
source_type: code
