aliases: []
creation_timestamp: 1690876860233
current_stage: Production
description: null
last_updated_timestamp: 1690876935302
name: autoencoder_32
run_id: 204341605fee4ab99835afe8288c42db
run_link: null
source: /home/borja/projects/deepaas_full/models/0/204341605fee4ab99835afe8288c42db/artifacts/model
status: READY
status_message: null
user_id: null
version: 2
