artifact_uri: /home/borja/projects/deepaas_full/models/0/204341605fee4ab99835afe8288c42db/artifacts
end_time: 1690876836496
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 204341605fee4ab99835afe8288c42db
run_name: languid-finch-341
run_uuid: 204341605fee4ab99835afe8288c42db
source_name: ''
source_type: 4
source_version: ''
start_time: 1690876480740
status: 3
tags: []
user_id: borja
