# .sqa/config.yml - jenkins-pipeline-library configuration file

# generic configuration: workspace, agents
config:
  project_repos:
    demo-advanced:
      repo: "https://github.com/deephdc/demo_advanced.git"
      branch: dev1

sqa_criteria:
  qc_style:
    repos:
      demo-advanced:
        container: testing
        tox_file: tox.ini
        tox:
          testenv:
            - qc.sty

environment:
  GIT_COMMITTER_NAME: "Borja Esteban"
  GIT_COMMITTER_EMAIL: boressan@outlook.com
  LANG: C.UTF-8

timeout: 600
