# .sqa/config.yml - jenkins-pipeline-library configuration file

# generic configuration: workspace, agents
config:
  project_repos:
    demo-advanced:
      repo: "https://github.com/deephdc/demo_advanced.git"
      branch: main 

sqa_criteria:
  qc_style:
    repos:
      demo-advanced:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sty
  qc_coverage:
    repos:
      demo-advanced:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.cov
  qc_security:
    repos:
      demo-advanced:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sec

environment:
  GIT_COMMITTER_NAME: "Borja Esteban"
  GIT_COMMITTER_EMAIL: boressan@outlook.com
  LANG: C.UTF-8

timeout: 600
