version: "3.6"

services:
  testing:
    image: ifcacomputing/ci-images:python3.11
    container_name: testing
    working_dir: /srv
    volumes:
      - type: bind
        source: ./
        target: /srv
    command: sleep infinity
