aliases: []
creation_timestamp: 1690782661547
current_stage: Production
description: null
last_updated_timestamp: 1690785319054
name: autoencoder_64
run_id: 59b34635a3c64307a4f0bdd5c41d167e
run_link: null
source: /home/borja/projects/deepaas_full/models/0/59b34635a3c64307a4f0bdd5c41d167e/artifacts/model
status: READY
status_message: null
user_id: null
version: 1
