aliases: []
creation_timestamp: 1690877131236
current_stage: Production
description: null
last_updated_timestamp: 1690877174024
name: autoencoder_64
run_id: c66d6ffbe3924d8c8030b0e79cf39e75
run_link: null
source: /home/borja/projects/demo-advanced-api/models/0/c66d6ffbe3924d8c8030b0e79cf39e75/artifacts/model
status: READY
status_message: null
user_id: null
version: 1
