aliases: []
creation_timestamp: 1690880342210
current_stage: Production
description: null
last_updated_timestamp: 1690880360051
name: dense2layers
run_id: 11428c08543340edb302f09ab1d4a373
run_link: null
source: /home/borja/projects/demo-advanced-api/models/0/11428c08543340edb302f09ab1d4a373/artifacts/model
status: READY
status_message: null
user_id: null
version: 1
