artifact_uri: /home/borja/projects/deepaas_full/models/0/076ad437da3e40b686c242a9eb855fee/artifacts
end_time: 1690882721669
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 076ad437da3e40b686c242a9eb855fee
run_name: resilient-squid-505
run_uuid: 076ad437da3e40b686c242a9eb855fee
source_name: ''
source_type: 4
source_version: ''
start_time: 1690882718174
status: 3
tags: []
user_id: borja
