artifact_uri: /home/borja/projects/deepaas_full/models/0/da16768c4d5b46cb8ea3e9007cf3ff4e/artifacts
end_time: 1690876449336
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: da16768c4d5b46cb8ea3e9007cf3ff4e
run_name: amazing-hound-929
run_uuid: da16768c4d5b46cb8ea3e9007cf3ff4e
source_name: ''
source_type: 4
source_version: ''
start_time: 1690876445787
status: 3
tags: []
user_id: borja
