artifact_uri: /home/borja/projects/deepaas_full/models/0/11428c08543340edb302f09ab1d4a373/artifacts
end_time: 1690880342198
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 11428c08543340edb302f09ab1d4a373
run_name: delightful-cub-790
run_uuid: 11428c08543340edb302f09ab1d4a373
source_name: ''
source_type: 4
source_version: ''
start_time: 1690880338912
status: 3
tags: []
user_id: borja
