artifact_uri: /home/borja/projects/demo-advanced-api/models/0/2b9409c8ff6e40efa4509add25d70065/artifacts
end_time: 1690877735943
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2b9409c8ff6e40efa4509add25d70065
run_name: powerful-skink-904
run_uuid: 2b9409c8ff6e40efa4509add25d70065
source_name: ''
source_type: 4
source_version: ''
start_time: 1690877186947
status: 3
tags: []
user_id: borja
