aliases: []
creation_timestamp: 1690880653467
current_stage: Production
description: null
last_updated_timestamp: 1690880714783
name: dense2layers
run_id: bbe3ef9450f747b9a34e99e3f3f43bd3
run_link: null
source: /home/borja/projects/demo-advanced-api/models/0/bbe3ef9450f747b9a34e99e3f3f43bd3/artifacts/model
status: READY
status_message: null
user_id: null
version: 2
