artifact_uri: /home/borja/projects/deepaas_full/models/0/c66d6ffbe3924d8c8030b0e79cf39e75/artifacts
end_time: 1690877131223
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c66d6ffbe3924d8c8030b0e79cf39e75
run_name: legendary-flea-843
run_uuid: c66d6ffbe3924d8c8030b0e79cf39e75
source_name: ''
source_type: 4
source_version: ''
start_time: 1690877127718
status: 3
tags: []
user_id: borja
